---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  selector:
    app: {{ .Values.appname }}
